name: CD - Deploy to Production

on:
  push:
    branches:
      - develop # For staging
      - main    # For production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Netlify
        run: npx netlify-cli deploy --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Rollback on failure
        if: failure()
        run: |
          echo "Deployment failed, rolling back to previous version..."
          npx netlify-cli rollback
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      
      - name: Notify Discord on Failure
        if: failure()
        run: |
            npm install
            npm run send-dm-discord
        env:
            DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
            DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}

      - name: Notify Discord on Success
        if: success()
        run: |
            npm install
            npm run send-dm-discord
        env:
            DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
            DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}

